(defpackage bakebot-srv
  (:use cl
        roslisp-msg-protocol)
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "<ADDTWOINTS-RESPONSE>"
   "MOVEEE"
   "<MOVEEE-REQUEST>"
   "<MOVEEE-RESPONSE>"
   "ATTACHDETACH"
   "<ATTACHDETACH-REQUEST>"
   "<ATTACHDETACH-RESPONSE>"
   "MIXBOWL"
   "<MIXBOWL-REQUEST>"
   "<MIXBOWL-RESPONSE>"
   "CLEANSPOON"
   "<CLEANSPOON-REQUEST>"
   "<CLEANSPOON-RESPONSE>"
   "BAKEBOTLOGEVENT"
   "<BAKEBOTLOGEVENT-REQUEST>"
   "<BAKEBOTLOGEVENT-RESPONSE>"
  ))

