(define (problem deal-1-bowl)
	(:domain deal-bowl)
	(:objects ingred
			  gripper)
	(:init (INGRED ingred)
		   (GRIPPER gripper)
		   (reset gripper)
		   (free gripper)
		   (on-table ingred)
		   (not (poured-out ingred))
		   (not (in-transit ingred))
		   (not (over-mb ingred))
		   (not (cardinal ingred))
		   (not (randomp ingred))
		   (not (inverted ingred))
		   (not (done ingred)))
	(:goal (and (poured-out ingred)
				(reset gripper))))
	
