(define (domain mix-ingreds)
	(:predicates (GRIPPER ?x) 
				 (MIXING-BOWL ?x) 
				 (SPATULA-GRIPPER ?x)
				 (carry ?x ?y)
				 (free ?x)
				 (over-mb ?x)
				 (reset-safe ?x)
				 (in-mb ?x)
				 (mix-zone ?x)
				 (mixed ?x)
				 (reset ?x))
	(:action servo-to-mb
		:parameters (?x)
		:precondition (not (mix-zone ?x))
		:effect (mix-zone ?x))
	(:action servo-from-mb
		:parameters (?x)
		:precondition (mix-zone ?x)
		:effect (not (mix-zone ?x)))
	(:action grab-mb 
		:parameters (?x ?y)
		:precondition (and (MIXING-BOWL ?x) 
						   (GRIPPER ?y) 
						   (not (SPATULA-GRIPPER ?y))
						   (reset ?y)
						   (free ?y)
						   (mix-zone ?x))
		:effect (and (carry ?y ?x) 
					 (not (free ?y))
					 (not (reset ?y))
					 (not (reset-safe ?y))))
	(:action transit-spoon
		:parameters (?y ?x ?z)
		:precondition (and (GRIPPER ?y) 
                           (MIXING-BOWL ?x)
                           (GRIPPER ?z)
                           (carry ?z ?x)
                           (mix-zone ?x)
						   (SPATULA-GRIPPER ?y))
		:effect (and (over-mb ?y)
					 (not (reset ?y))
					 (not (reset-safe ?y))))
	(:action plunge-spoon
		:parameters (?y ?x ?z)
		:precondition (and (GRIPPER ?y) 
						   (SPATULA-GRIPPER ?y)
                           (GRIPPER ?x)
                           (MIXING-BOWL ?z)
                           (carry ?x ?z)
						   (over-mb ?y))
		:effect (and (not (over-mb ?y))
					 (in-mb ?y)))
	(:action mix
		:parameters (?left ?right ?mb)
		:precondition (and (GRIPPER ?left) 
						   (not (SPATULA-GRIPPER ?left))
						   (GRIPPER ?right)
						   (SPATULA-GRIPPER ?right)
						   (MIXING-BOWL ?mb)
						   (carry ?left ?mb)
						   (in-mb ?right))
		:effect (mixed ?mb))
	(:action deplunge-spoon
		:parameters (?y)
		:precondition (and (GRIPPER ?y) 
						   (SPATULA-GRIPPER ?y)
						   (in-mb ?y))
		:effect (and (not (in-mb ?y))
					 (over-mb ?y)))
	(:action retreat-spoon
		:parameters (?y ?x ?z)
		:precondition (and (GRIPPER ?y) 
                           (GRIPPER ?x)
                           (MIXING-BOWL ?z)
                           (carry ?x ?z)
						   (SPATULA-GRIPPER ?y))
		:effect (and (not (over-mb ?y))
                     (not (in-mb ?y))
					 (reset-safe ?y)))
	(:action retreat-grab
		:parameters (?x ?y)
		:precondition (and (GRIPPER ?y) 
                           (MIXING-BOWL ?x)
						   (not (SPATULA-GRIPPER ?y))
                           (not (free ?y)))
		:effect (and (free ?y)
                     (not (carry ?y ?x))
					 (reset-safe ?y)))
	(:action reset
		:parameters (?x)
		:precondition (and (GRIPPER ?x) 
                           (reset-safe ?x))
		:effect (and (reset ?x)))
)
