#cloud of points with normals that we want to plan around
geometry_msgs/Pose object_pose
float32 radius
float32 angle
---
#path around the object, arcing to keep a distance of radius from the object
geometry_msgs/PoseArray path

